package boardr.commands.common;

public enum CommandType {

    CREATEBOARDITEM,
    CREATETASK,
    OPENISSUE,
    CHANGEASSIGNEE,
    CHANGEITEMTITLE,
    CHANGEITEMDUEDATE,
    ADVANCEITEMSTATUS,
    REVERTITEMSTATUS,
    VIEWITEMINFO,
    DISPLAYLOCALHISTORY,
    CREATELOG,
    DISPLAYEVENTLOG,
    BOARDADDITEM,
    BOARDREMOVEITEM,
    BOARDPRINTLIST,
    BINPRINTLIST,
    CLEARBIN;
}
