package boardr.commands;

public enum CommandType {

    CREATEBOARDITEM,
    CREATETASK,
    OPENISSUE,
    CHANGEITEMTITLE,
    CHANGEITEMDUEDATE,
    ADVANCEITEMSTATUS,
    REVERTITEMSTATUS,
    VIEWITEMINFO,
    DISPLAYLOCALHISTORY,
    CREATELOG,
    DISPLAYHISTORY,
    BOARDADDITEM,
    BOARDREMOVEITEM,
    BOARDPRINTLIST,
    BOARDGETTOTALITEMS;
}
