package com.company.oop.cosmetics.commands.enums;

public enum CommandType {
    CREATECATEGORY,
    ADDTOCATEGORY,
    SHOWCATEGORY,
    SHOWPRODUCT,
    CREATEPRODUCT,
    ADDTOSHOPPINGCART,
    REMOVEFROMSHOPPINGCART,
    REMOVEFROMCATEGORY,
    TOTALPRICE;
}
